site_name: "Mu-Pipelines Docs"
theme:
  name: "material"

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Execute Commands: execute-command
  - Destination Commands: destinations-commands
  - FAQ: faq.md

repo_url: "https://github.com/your-repo/mu-pipelines"
