site_name: "Mu-Pipelines Docs"
theme:
  name: "material"

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Execute Commands: 
      Read from CSV: ingest-command\ingestCSV.md
      Read from Kafka: ingest-command\ingestKafka.md
  - Transform Commands: 
      SQL Transformation: transform-command\transformSQL.md
  - Destination Commands: 
      Write to CSV: destination-command\destinationCSV.md
      Store to Iceberg: destination-command\destinationIceberg.md
  - Streaming Commands: 
      Kafka to Iceberg Configuration: streaming-command\stream-kafka-iceberg.md

  - FAQ: faq.md

repo_url: "https://mosaicsoft-data.github.io/mu-pipelines-doc/"
