site_name: "Mu-Pipelines Docs"
theme:
  name: "material"

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Execute Commands: execute-command\execute-command.md
  - Destination Commands: destination-commands\destination-command.md
  - Streaming Commands: streaming-commands\streaming-command.md
  - FAQ: faq.md

repo_url: "https://github.com/your-repo/mu-pipelines"
