site_name: "Mu-Pipelines Docs"
theme:
  name: "material"

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Execute Commands: execute-command\execute-command.md
  - Destination Commands: destination-command\destination-command.md
  - Streaming Commands: streaming-command\streaming-command.md
  - FAQ: faq.md

repo_url: "https://mosiacsoft.github.io/mu-pipelines-doc/"
