site_name: "mu-pipelines Docs"
theme:
  name: "material"
plugins:
    - mkdocs-video:
        is_video: True
        video_muted: True
        video_controls: True
        css_style:
        width: "50%"
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Ingestion Commands: 
      CSV: ingest-command\ingestCSV.md
      Kafka: ingest-command\ingestKafka.md
      Databases (JDBC): ingest-command\ingestJDBC.md
  - Transform Commands: 
      SQL Transformation: transform-command\transformSQL.md
  - Destination Commands: 
      CSV: destination-command\destinationCSV.md
      Deafult Catalog (Data Lake/Lakehouse): destination-command\destinationDefaultCatalog.md
  - Streaming Commands: 
      Kafka to Iceberg Configuration: streaming-command\stream-kafka-iceberg.md
  - Connection Properties: connection_properties.md
  - Global Properties: global_properties.md
  - Developer Docs: 
      CI-CD: Developer Docs\CI-CD.md
      How to create data mesh: Developer Docs\How to create data mesh.md
  - Demo Videos: 
      Introduction: Demo Videos\Introduction.md
      Basic Setup: Demo Videos\Basic Setup.md
      Use in databricks: Demo Videos\Use in databricks.md
  - FAQ: faq.md

repo_url: "https://mosaicsoft-data.github.io/mu-pipelines-doc/"
