site_name: "Mu-Pipelines Docs"
theme:
  name: "material"

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Configuration: config.md
  - Running Pipelines: running.md
  - Connectors: connectors.md
  - FAQ: faq.md

repo_url: "https://github.com/your-repo/mu-pipelines"
